---

- hosts: postgre_rsa
  become: true
  become_user: root
  vars:
    users:
    - username: "x1"
    - username: "x2"
    - username: "x3"
    - username: "x4"
    - username: "x5"

  tasks:

    - name : create users
      ansible.builtin.user:
        name: "{{ item.username }}"
        shell: /bin/bash
      with_items: "{{ users }}"

    - name : Create .ssh folder
      file:
        path: /home/{{ item.username  }}/.ssh
        state: directory
        owner: "{{ item.username }}"
        group: "{{ item.username }}"
        mode: 0700
      with_items: "{{ users }}"

    - name: Transfer authorized_keys into the .ssh folder
      ansible.builtin.copy:
        src:  /home/USER_RSA/scripts/yaml/postgre/users/{{ item.username  }}/authorized_keys
        dest: /home/{{ item.username }}/.ssh/
        owner: "{{ item.username }}"
        group: "{{ item.username }}"
        mode: 0600
      with_items: "{{ users }}"

    - name: Giving write permission to /etc/sudoers file
      shell: "{{ item }}"
      with_items:
          - chmod +w /etc/sudoers

    - name: Adding user {{ user }} to wheel sudo group
      user:
        name: "{{ item.username }}"
        groups: wheel
        append: yes
      with_items: "{{ users }}"


    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
