- hosts: redis
  become: true
  become_user: root
  roles:
    - role: elastic.elasticsearch
  vars:
    es_heap_size: "1g"
    es_config:
      cluster.name: "test-cluster"
      cluster.initial_master_nodes: 192.168.xxx, 192.168.xxx1, 192.168.xxx2
      discovery.seed_hosts: 192.168.xxx, 192.168.xxx1, 192.168.xxx2
      http.port: 9200
      node.name: NODEHOSTNAME
      network.host: 0.0.0.0
      node.data: false
      node.master: true
      bootstrap.memory_lock: false
    es_plugins:
     - plugin: ingest-attachment

