- hosts: db_patch_2
  become: true
  become_user: root
  vars:
    user_names:
      - 'x1'
      - 'x2'
      - 'x3'


  tasks:
    - name: Remove Users
      user:
        name: '{{ item }}'
        state: absent
        remove: yes
      loop: "{{ user_names }}"
