---

- name: Install Rabbitmq Cluster Server
  hosts: rabbitmq-master
  become: yes
  remote_user: root
  tasks:
    - name: erlang repo add
      shell: "{{ item }}"
      with_items:
          - touch /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "[rabbitmq_erlang]" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "name=rabbitmq_erlang " >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "baseurl=https://packagecloud.io/rabbitmq/erlang/el/8/x86_64 " >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "repo_gpgcheck=1" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "gpgcheck=1" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "enabled=1" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "# PackageCloud's repository key and RabbitMQ package signing key " >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "gpgkey=https://packagecloud.io/rabbitmq/erlang/gpgkey" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "       https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "sslverify=1" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "sslcacert=/etc/pki/tls/certs/ca-bundle.crt" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "metadata_expire=300" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "[rabbitmq_erlang-source] " >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "name=rabbitmq_erlang-source" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "baseurl=https://packagecloud.io/rabbitmq/erlang/el/8/SRPMS" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "repo_gpgcheck=1" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "gpgcheck=0" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "enabled=1" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "# PackageCloud's repository key and RabbitMQ package signing key" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "gpgkey=https://packagecloud.io/rabbitmq/erlang/gpgkey" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "       https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "sslverify=1" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "sslcacert=/etc/pki/tls/certs/ca-bundle.crt" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "metadata_expire=300" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - yum makecache -y

    - name: yum update all package
      yum: name={{ item }} state=present
      with_items:
          - erlang

    - name: cluster master configuration
      shell: "{{ item }}"
      with_items:
          - echo "xxxx AAAAAA" >> /etc/hosts


  roles:
    - tanadeau.ansible_role_rabbitmq
  vars:
    - rabbitmq_version: "3.8.9"
    - rabbitmq_daemon: rabbitmq-server
    - rabbitmq_state: started
    - rabbitmq_enabled: true

- name : Install rabbitMq Second node
  hosts: rabbitmq-slave
  become: yes
  remote_user: root
  tasks:
    - name: erlang repo add
      shell: "{{ item }}"
      with_items:
          - touch /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "[rabbitmq_erlang]" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "name=rabbitmq_erlang " >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "baseurl=https://packagecloud.io/rabbitmq/erlang/el/8/x86_64 " >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "repo_gpgcheck=1" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "gpgcheck=1" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "enabled=1" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "# PackageCloud's repository key and RabbitMQ package signing key " >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "gpgkey=https://packagecloud.io/rabbitmq/erlang/gpgkey" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "       https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "sslverify=1" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "sslcacert=/etc/pki/tls/certs/ca-bundle.crt" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "metadata_expire=300" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "[rabbitmq_erlang-source] " >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "name=rabbitmq_erlang-source" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "baseurl=https://packagecloud.io/rabbitmq/erlang/el/8/SRPMS" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "repo_gpgcheck=1" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "gpgcheck=0" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "enabled=1" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "# PackageCloud's repository key and RabbitMQ package signing key" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "gpgkey=https://packagecloud.io/rabbitmq/erlang/gpgkey" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "       https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "sslverify=1" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "sslcacert=/etc/pki/tls/certs/ca-bundle.crt" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - echo "metadata_expire=300" >> /etc/yum.repos.d/rabbitmq_erlang.repo
          - yum makecache -y

    - name: yum update all package
      yum: name={{ item }} state=present
      with_items:
          - erlang

    - name: cluster master configuration
      shell: "{{ item }}"
      with_items:
          - echo "yyyyy BBBBB" >> /etc/hosts


  roles:
    - tanadeau.ansible_role_rabbitmq
  vars:
    - rabbitmq_version: "3.8.9"
    - rabbitmq_daemon: rabbitmq-server
    - rabbitmq_state: started
    - rabbitmq_enabled: true


- name: Install Rabbitmq Cluster Server
  hosts: rabbitmq-master
  become: yes
  remote_user: root
  tasks:
    - name: erlang cookie copy
      shell: "{{ item }}"
      with_items:
          - systemctl restart rabbitmq-server.service
          - rabbitmqctl add_user admin2 123qwe
          - rabbitmqctl set_user_tags admin2 administrator
          - scp /var/lib/rabbitmq/.erlang.cookie root@192.168.186.97:/var/lib/rabbitmq/



- name: stop rabbitmq service node2
  hosts: rabbitmq-slave
  become: yes
  remote_user: root
  tasks:
    - name:
      shell: "{{ item }}"
      with_items:
          - systemctl restart rabbitmq-server.service
          - rabbitmqctl stop_app
          - rabbitmqctl reset
          - rabbitmqctl join_cluster rabbit@AAAAAA
          - rabbitmqctl start_app
