---

- name: Redis Cluster Installation
  hosts: redis
  become: true
  become_user: root
  pre_tasks:
        - name: redis remove
          shell: "{{ item }}"
          with_items:
              - yum remove -y redis
              - rm -rf /var/lib/redis*
              - rm -rf /etc/redis*

        - name: redis replica conf move
          copy:
            src: /home/odeonuser/management/redis.conf_rename
            dest: /etc/redis.conf_rename
             
        - name: redis sentinel scp
          copy:
            src: /home/odeonuser/management/redis-sentinel.conf_rename
            dest: /etc/redis-sentinel.conf_rename

        - name: server settings
          shell: "{{ item }}"
          with_items:
              - sh -c 'echo "never" > /sys/kernel/mm/transparent_hugepage/enabled'
              - echo "echo never > /sys/kernel/mm/transparent_hugepage/enabled" | sudo tee -a /etc/rc.local
              - echo net.core.somaxconn = 65535 | sudo tee -a /etc/sysctl.conf
              - sysctl -w net.core.somaxconn=65535
              - sh -c 'echo "65535" > /proc/sys/net/core/somaxconn'
              - echo "MASTER HOSTNAME" >> /etc/hosts
              - echo "SLAVE1 HOSTNAME" >> /etc/hosts
              - echo "SLAVE2 HOSTNAME" >> /etc/hosts
              - curl -L -O https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && yum install epel-release-latest-7.noarch.rpm -y
              - yum makecache -y
              - yum repolist all
              - yum install redis -y
              - systemctl start redis
              - systemctl enable redis
              - mv /etc/redis-sentinel.conf /etc/redis-sentinel.conf_orig
              - mv /etc/redis.conf /etc/redis.conf_orig
              - mv /etc/redis.conf_rename /etc/redis.conf
              - mv /etc/redis-sentinel.conf_rename  /etc/redis-sentinel.conf
              - mkdir -p /var/lib/redis-sentinel
              - chown -R redis:redis /var/lib/redis-sentinel
              - sed -i 's/sentinel monitor REDIS_TEST MASTER PORT 22/sentinel monitor REDIS_TEST MASTER 6379 2/g' /etc/redis-sentinel.conf
              - systemctl restart redis.service

- name: Redis Node Configuration Slave Node 1
  hosts: redis-slave1
  become: yes
  become_user: root
  tasks:
    - name: Slave 1 Configuration
      shell: "{{ item }}"
      with_items:
          - sed -i 's/slave-priority 100/slave-priority 150/g' /etc/redis.conf
          - echo "slaveof MASTER PORT" >> /etc/redis.conf
          - echo "# Generated by CONFIG REWRITE" >> /etc/redis-sentinel.conf
          - echo "supervised systemd" >> /etc/redis-sentinel.conf
          - echo "sentinel config-epoch REDIS_TEST 4" >> /etc/redis-sentinel.conf
          - echo "sentinel leader-epoch REDIS_TEST 4" >> /etc/redis-sentinel.conf
          - echo "sentinel known-slave  REDIS_TEST SLAVE1 PORT" >> /etc/redis-sentinel.conf
          - echo "sentinel known-slave  REDIS_TEST SLAVE2 PORT" >> /etc/redis-sentinel.conf
          - echo "sentinel known-sentinel REDIS_TEST MASTER1 PORT" >> /etc/redis-sentinel.conf
          - echo "sentinel known-sentinel REDIS_TEST SLAVE2 PORT" >> /etc/redis-sentinel.conf
          - echo "sentinel current-epoch 4" >> /etc/redis-sentinel.conf
          - systemctl restart redis.service
          - systemctl restart redis-sentinel.service

- name: Redis Node Configuration Slave Node 2
  hosts: redis-slave2
  become: yes
  become_user: root
  tasks:
    - name: Slave 2 Configuration
      shell: "{{ item }}"
      with_items:
          - sed -i 's/slave-priority 100/slave-priority 200/g' /etc/redis.conf
          - echo "" >> /etc/redis.conf
          - echo "slaveof MASTER PORT" >> /etc/redis.conf
          - echo "# Generated by CONFIG REWRITE" >> /etc/redis-sentinel.conf
          - echo "supervised systemd" >> /etc/redis-sentinel.conf
          - echo "sentinel config-epoch REDIS_TEST 4" >> /etc/redis-sentinel.conf
          - echo "sentinel leader-epoch REDIS_TEST 4" >> /etc/redis-sentinel.conf
          - echo "sentinel known-slave  REDIS_TEST SLAVE1 PORT" >> /etc/redis-sentinel.conf
          - echo "sentinel known-slave  REDIS_TEST SLAVE2 PORT" >> /etc/redis-sentinel.conf
          - echo "sentinel known-sentinel REDIS_TEST MASTER PORT" >> /etc/redis-sentinel.conf
          - echo "sentinel known-sentinel REDIS_TEST SLAVE1 PORT" >> /etc/redis-sentinel.conf
          - echo "sentinel current-epoch 4" >> /etc/redis-sentinel.conf
          - systemctl restart redis.service
          - systemctl restart redis-sentinel.service
