- hosts: test_auth
  become: true
  become_user: root
  tasks:

    - name: User Add USERNAME
      ansible.builtin.user:
       name: USERNAME
       shell: /bin/bash
      when: "{{ inventory_hostname == 'NEW_IPADDRESS' }}"

    - name : Create .ssh folder
      file:
        path: /home/USERNAME/.ssh
        state: directory
        owner: USERNAME
        group: USERNAME
        mode: 0700
      when: "{{ inventory_hostname == 'NEW_IPADDRESS' }}"

    - name: Fetch the file from the  to PROXY_MACHINE
      run_once: yes
      fetch: src=/home/berfin/.ssh/authorized_keys dest=buffer/ flat=yes
      when: "{{ inventory_hostname == 'PROXY_MACHINE' }}"

    - name: Copy the file from master to 186.95
      copy: src=buffer/authorized_keys dest=/home/USERNAME/.ssh/
      when: "{{ inventory_hostname == 'NEW_IPADDRESS' }}"


    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /home/USERNAME/.ssh/authorized_keys
        owner: USERNAME
        group: USERNAME
        mode: '0600'
      when: "{{ inventory_hostname == 'NEW_MACHINE' }}"
