---

- hosts: redis
  become: true
  become_user: root
  tasks:
       - name: Atop and PSACCT Install
         yum:
           name:
             - atop
             - psacct
           state: present

       - name: Enable Atop
         service:
           name: atop
           enabled: yes

       - name: Enable Start
         service:
           name: psacct
           state: started
