---

- hosts: redis
  become: true
  become_user: root
  tasks:
       - name: Atop and PSACCT Install
         yum:
           name:
             - atop
             - psacct
           state: present
